### ISSUE TITLE
closestream.h fails to build in libuuid-1.4

### ISSUE THREAD

**Issue by trappedinspacetime** [JackieXie168/libuuid#1]
Thank you for this repo.
I get the following error message on Ubuntu 16.04

    In file included from uuidgen.c:36:0:
    closestream.h:54:1: error: static declaration of ‘fsync’ follows non-static declaration
     fsync(int fd __attribute__((__unused__)))
     ^
    In file included from c.h:24:0,
                 from uuidgen.c:35:
    /usr/include/unistd.h:959:12: note: previous declaration of ‘fsync’ was here
     extern int fsync (int __fd);
            ^
Replacing the header file with [this](https://raw.githubusercontent.com/leonmzhang/ztools/7d53794c9c66f2bcc6f5aca0428df525c4628f1c/include/closestream.h) fixed the error.
